name: CI Poster
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
    paths:
      - 'poster/**'

jobs:
  build:
    name: Build poster PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Bibtex file
        run: curl https://www.dropbox.com/s/r3gxfmijiqfd62d/library.bib?dl=1 -o bibtex.bib
      - name: Run Pandoc
        uses: docker://pandoc/latex:2.9
        with:
          args: poster/*.md --defaults=defaults/poster.yaml
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
