name: CI Poster
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
    paths:
      - 'poster/**'

jobs:
  build:
    name: Build poster PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Bibtex file
        run: curl https://www.dropbox.com/s/r3gxfmijiqfd62d/library.bib?raw=1 -L -o bibtex.bib
      - name: Make output folder
        run: mkdir output
      - name: Copy poster folder files to root
        run: cp poster/*.md .
      - name: List markdown files
        run: echo "::set-output name=md_files::$(ls -1 *.md | tr  '\n' ' ')"
        id: input_files
      - name: Run Pandoc
        uses: docker://pandoc/latex:2.9.2
        with:
          entrypoint: /bin/sh
          args: >-
            -c "
             tlmgr update --self &&
             tlmgr install beamerposter type1cm libertine inconsolata newtx txfonts &&
             pandoc --defaults=defaults/poster.yaml ${{ steps.input_files.outputs.md_files }}
            "
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
