name: CI Poster
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
    paths:
      - 'poster/**'

jobs:
  build:
    name: Build poster PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout poster folder
        uses: actions/checkout@v2
      - name: List contents
        run: ls poster/*.md
