name: CI Poster
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
    paths:
      - 'poster/**'

jobs:
  build:
    name: Build poster PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make output folder
        run: mkdir output && mkdir output/images
      - name: Download Bibtex file
        run: curl $BIBTEX_LINK -L -o output/bibtex.bib
        env: 
          BIBTEX_LINK: ${{ secrets.BIBTEX_LINK }}
      - name: List markdown files
        run: echo "::set-output name=md_files::$(ls -1 poster/*.md | tr  '\n' ' ')"
        id: input_files
      - name: Run Pandoc
        uses: docker://pandoc/latex:2.9.2
        with:
          entrypoint: /bin/sh
          args: >-
            -c "
             tlmgr update --self &&
             tlmgr install texliveonfly &&
             apk add curl git python2 &&
             curl https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.6.2/linux-pandoc_2_9_2.tar.gz -L -O &&
             tar -C /usr/bin -zxvf linux-pandoc_2_9_2.tar.gz &&
             rm linux-pandoc_2_9_2.tar.gz &&
             pandoc --defaults=defaults/poster.yaml --output=output/poster.tex --to=latex ${{ steps.input_files.outputs.md_files }} &&
             texliveonfly output/poster.tex &&
             pandoc --defaults=defaults/poster.yaml ${{ steps.input_files.outputs.md_files }}
            "
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
