name: CI Poster
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
    paths:
      - 'poster/**'

jobs:
  build:
    name: Build poster PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Bibtex file
        run: curl https://www.dropbox.com/s/r3gxfmijiqfd62d/library.bib?dl=1 -o bibtex.bib
      - name: Remove executable bit
        run: sudo chmod -x poster/*.md
      - name: List markdown files
        run: echo "::set-output name=md_files::$(ls -1 poster/*.md | tr  '\n' ' ')"
        id: input_files
      - name: Run Pandoc
        uses: docker://pandoc/latex:2.9.2
        with:
          args: ${{ steps.input_files.outputs.md_files }} --defaults=defaults/poster.yaml
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
