name: CI Poster
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
    paths:
      - 'poster/**'

jobs:
  build:
    name: Build poster PDF
    runs-on: ubuntu-latest
    steps:
      - name: Run Pandoc
        uses: docker://pandoc/latex:2.9
        args: |>
          --defaults=defaults/poster.yaml
          poster/*.md
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
